Device: cuda
Dataset: cityscapes, Train set: 233, Val set: 59
Model restored from /home/shubhamp/Downloads/DeepLabV3Plus-binaryclassification/checkpoints/CITY_768x768/best_deeplabv3plus_mobilenet_cityscapes_os8.pth
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 364, in <module>
    main()
  File "main.py", line 284, in main
    val_score, ret_samples = validate(opts=opts, model=model, loader=val_loader, device=device, binary_metrics= binary_metrics, ret_samples_ids=vis_sample_id)
  File "main.py", line 159, in validate
    wandb.log({"Validation Accuracy": binary_metrics.get_accuracy(),
AttributeError: 'BinaryClassificationMetrics' object has no attribute 'get_accuracy'
Image Name: PE-UP-7086-90_2_leftImg8bit, Predicted Label: 0.0
Image Name: PE-UP-41886-59_2_leftImg8bit, Predicted Label: 0.0
Image Name: PE-UP-24580-85_1_leftImg8bit, Predicted Label: 0.0
Image Name: PE-UP-24581-62_2_leftImg8bit, Predicted Label: 0.0